runs_dir: output
seed: 13
frames: 10

inpainting_prompt: "POV, walkthrough, a medieval dungeon with damp, stone corridors and flickering torches lining the walls, beautiful photo, masterpiece, indoor scene"
